"""add_suggested_title_extracted_grade

Revision ID: 1c76a74274e9
Revises: 20260125_add_exam_metadata
Create Date: 2026-01-25 03:14:13.430223
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '1c76a74274e9'
down_revision: Union[str, None] = '20260125_add_exam_metadata'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
