"""add_grading_status

Revision ID: 243364f0c7df
Revises: c0f6b4cc5a65
Create Date: 2026-01-25 01:39:21.804435
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '243364f0c7df'
down_revision: Union[str, None] = 'c0f6b4cc5a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('grading_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'grading_status')
    # ### end Alembic commands ###
