"""add_exam_type

Revision ID: 96c31afea73c
Revises: 20260124_extensions
Create Date: 2026-01-24 21:54:49.667727
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '96c31afea73c'
down_revision: Union[str, None] = '20260124_extensions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_analysis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('total_feedback_count', sa.Integer(), nullable=False),
    sa.Column('feedback_stats', sa.JSON(), nullable=False),
    sa.Column('improvement_suggestions', sa.JSON(), nullable=False),
    sa.Column('auto_applied_count', sa.Integer(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learned_patterns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pattern_type', sa.String(length=50), nullable=False),
    sa.Column('pattern_key', sa.String(length=200), nullable=False),
    sa.Column('pattern_value', sa.Text(), nullable=False),
    sa.Column('apply_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learned_patterns_pattern_type'), 'learned_patterns', ['pattern_type'], unique=False)
    op.create_table('problem_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('problem_types',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('grade_levels', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('core_concepts', sa.JSON(), nullable=False),
    sa.Column('prerequisite_types', sa.JSON(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('accuracy_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['problem_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_types_category_id'), 'problem_types', ['category_id'], unique=False)
    op.create_table('error_patterns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('problem_type_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=50), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('wrong_examples', sa.JSON(), nullable=False),
    sa.Column('correct_examples', sa.JSON(), nullable=False),
    sa.Column('feedback_message', sa.Text(), nullable=False),
    sa.Column('feedback_detail', sa.Text(), nullable=True),
    sa.Column('difficulty_distribution', sa.JSON(), nullable=False),
    sa.Column('detection_keywords', sa.JSON(), nullable=False),
    sa.Column('detection_rules', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['problem_type_id'], ['problem_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_patterns_problem_type_id'), 'error_patterns', ['problem_type_id'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('problem_type_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('accuracy_score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['problem_type_id'], ['problem_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_problem_type_id'), 'prompt_templates', ['problem_type_id'], unique=False)
    op.create_table('pattern_examples',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('error_pattern_id', sa.String(length=36), nullable=False),
    sa.Column('problem_text', sa.Text(), nullable=False),
    sa.Column('problem_image_path', sa.String(length=500), nullable=True),
    sa.Column('student_answer', sa.Text(), nullable=False),
    sa.Column('student_process', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('correct_process', sa.Text(), nullable=True),
    sa.Column('ai_analysis', sa.JSON(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('exam_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['error_pattern_id'], ['error_patterns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pattern_examples_error_pattern_id'), 'pattern_examples', ['error_pattern_id'], unique=False)
    op.create_table('pattern_match_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('problem_type_id', sa.String(length=36), nullable=True),
    sa.Column('error_pattern_id', sa.String(length=36), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('prompt_template_ids', sa.JSON(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('feedback_received', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_results.id'], ),
    sa.ForeignKeyConstraint(['error_pattern_id'], ['error_patterns.id'], ),
    sa.ForeignKeyConstraint(['problem_type_id'], ['problem_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pattern_match_history_analysis_id'), 'pattern_match_history', ['analysis_id'], unique=False)
    # Add exam_type column with 3-step approach for existing data
    # Step 1: Add column as nullable
    op.add_column('exams', sa.Column('exam_type', sa.String(length=20), nullable=True))
    # Step 2: Set default value for existing rows
    op.execute("UPDATE exams SET exam_type = 'blank' WHERE exam_type IS NULL")
    # Step 3: Make column non-nullable
    op.alter_column('exams', 'exam_type', nullable=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'exam_type')
    op.drop_index(op.f('ix_pattern_match_history_analysis_id'), table_name='pattern_match_history')
    op.drop_table('pattern_match_history')
    op.drop_index(op.f('ix_pattern_examples_error_pattern_id'), table_name='pattern_examples')
    op.drop_table('pattern_examples')
    op.drop_index(op.f('ix_prompt_templates_problem_type_id'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_error_patterns_problem_type_id'), table_name='error_patterns')
    op.drop_table('error_patterns')
    op.drop_index(op.f('ix_problem_types_category_id'), table_name='problem_types')
    op.drop_table('problem_types')
    op.drop_table('problem_categories')
    op.drop_index(op.f('ix_learned_patterns_pattern_type'), table_name='learned_patterns')
    op.drop_table('learned_patterns')
    op.drop_table('feedback_analysis')
    # ### end Alembic commands ###
