"""add_detected_type_to_exam

Revision ID: c0f6b4cc5a65
Revises: e2f4f30bf5d7
Create Date: 2026-01-25 01:08:15.081344
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c0f6b4cc5a65'
down_revision: Union[str, None] = 'e2f4f30bf5d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('detected_type', sa.String(length=20), nullable=True))
    op.add_column('exams', sa.Column('detection_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'detection_confidence')
    op.drop_column('exams', 'detected_type')
    # ### end Alembic commands ###
