"""Add analysis tables

Revision ID: df53cb237e61
Revises: 20260123_100320
Create Date: 2026-01-24 02:17:22.918056
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'df53cb237e61'
down_revision: Union[str, None] = '20260123_100320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.Enum('IMAGE', 'PDF', name='filetypeenum', native_enum=False, length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ANALYZING', 'COMPLETED', 'FAILED', name='examstatusenum', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_user_id'), 'exams', ['user_id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exam_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_exam_id'), 'analysis_results', ['exam_id'], unique=True)
    op.create_index(op.f('ix_analysis_results_user_id'), 'analysis_results', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_results_user_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_exam_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_exams_user_id'), table_name='exams')
    op.drop_table('exams')
    # ### end Alembic commands ###
