"""Add pattern system tables

Revision ID: e2f4f30bf5d7
Revises: 96c31afea73c
Create Date: 2026-01-24 21:58:14.110846
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e2f4f30bf5d7'
down_revision: Union[str, None] = '96c31afea73c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
